name: Profiling
on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
jobs:
  baseline:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and run server
        run: |
          echo "building\n"
          make build=release

          echo "starting server\n"
          ./build/main 5980 &

          echo "SERVER_PID=$!" >> $GITHUB_ENV

      - name: Run benchmarking
        run: |
          sleep 2
          python benchmark.py > benchmark_results.txt
          
      - name: Display quick benchmarking result
        run: cat benchmark_results.txt
        
      - name: Peek server.log
        run: head -n 50 server.log

  on-cpu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
              
      - name: Install Profiling Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-$(uname -r)
          git clone --depth 1 https://github.com/brendangregg/FlameGraph

      - name: Configure Kernel Permissions
        run: |
          sudo sysctl -w kernel.perf_event_paranoid=-1
          sudo sysctl -w kernel.kptr_restrict=0
          
      - name: Build and run server
        run: |
          echo "building\n"
          make build=release

          echo "starting server\n"
          ./build/main 5980 &

          echo "SERVER_PID=$!" >> $GITHUB_ENV
          
      - name: Start Perf Recording
        run: |
          perf record -F 299 -p $SERVER_PID -g -o perf.data &
          echo "PERF_PID=$!" >> $GITHUB_ENV
          
      - name: Run benchmarking
        run: |
          sleep 2
          python benchmark.py > benchmark_results.txt

      - name: Stop Profiler and Server
        if: always()
        run: |
          if [ -n "$PERF_PID" ]; then kill -2 $PERF_PID; sleep 2; fi
          if [ -n "$SERVER_PID" ]; then kill $SERVER_PID; fi

      - name: Generate FlameGraph
        if: always()
        run: |
          # Convert perf.data to human-readable script output
          perf script -i perf.data > out.perf
          
          # Collapse stacks and render to SVG
          ./FlameGraph/stackcollapse-perf.pl out.perf > out.folded
          ./FlameGraph/flamegraph.pl out.folded > oncpu-flamegraph.svg
          
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oncpu-reports
          path: |
            benchmark_results.txt
            server.log
            oncpu-flamegraph.svg
            perf.data
            
      - name: Display quick benchmarking result
        run: cat benchmark_results.txt
      - name: Peek server.log
        run: |
          if [ -f "server.log" ]; then
            head -n 50 "server.log"
          else
            echo "No log, skipping..."
          fi

  off-cpu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
              
      - name: Install Profiling Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-$(uname -r)
          git clone --depth 1 https://github.com/brendangregg/FlameGraph
                    
      - name: Configure Kernel Permissions
        run: |
          sudo sysctl -w kernel.perf_event_paranoid=-1
          sudo sysctl -w kernel.kptr_restrict=0
          
      - name: Build and run server
        run: |
          make build=release
          ./build/main 5980 &
          echo "SERVER_PID=$!" >> $GITHUB_ENV
          
      - name: Start Off-CPU Recording
        run: |
          sudo perf record --off-cpu -e dummy -p $SERVER_PID -g -o offcpu.data &
          echo "PERF_PID=$!" >> $GITHUB_ENV
          
      - name: Run benchmarking
        run: |
          sleep 5
          python benchmark.py > benchmark_results.txt

      - name: Stop Profiler and Server
        if: always()
        run: |
          if [ -n "$PERF_PID" ]; then sudo kill -2 $PERF_PID; sleep 5; fi
          if [ -n "$SERVER_PID" ]; then kill $SERVER_PID || true; fi

      - name: Generate Off-CPU FlameGraph
        if: always()
        run: |
          sudo chmod 666 offcpu.data
          perf script -i offcpu.data > offcpu.perf
          ./FlameGraph/stackcollapse-perf.pl offcpu.perf > offcpu.folded
          ./FlameGraph/flamegraph.pl --color=io --title="Off-CPU Flame Graph" offcpu.folded > offcpu_flamegraph.svg
      
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: offcpu-reports
          path: |
            benchmark_results.txt
            server.log
            offcpu_flamegraph.svg
            
      - name: Display quick benchmarking result
        run: cat benchmark_results.txt
      - name: Peek server.log
        run: |
          if [ -f "server.log" ]; then
            head -n 50 "server.log"
          else
            echo "No log, skipping..."
          fi
